/**
 * \file	milbus.h
 *
 * \brief	File for declaration of types and constants for 1553 MILBUS bus.
 *
 * \author	Vito Capobianco, <vito.capobianco_at_oato.inaf.it>
 *
 * \internal
 *  Created on: 08/feb/2016
 */

#ifndef MILBUS_H_
#define MILBUS_H_

#include <public/mil_std_1553_common_mdpa_reg_mem.h>
#include <public/mil_std_1553_rt_reg_mem.h>
#include <public/mil_std_1553_bc_drv.h>

/**
 *  \ingroup MILBUS_MANAGER_CONSTANTS
 *  \{
 */

/**
 * The maximum length of the TMs generated by the RT
 * REQ-0940
 */
#define MIL_1553_MAX_TM_PKT_LENGTH 1024U //!< Maximum size in byte of a PUS TM packet
/**
 * The maximum length of the TCs generated by the BC
 * REQ-0950
 */
#define MIL_1553_MAX_TC_PKT_LENGTH 1016U //!< Maximum size in byte of a PUS TC packet
#define MIL_1553_MIN_TC_PKT_LENGTH 12U //!< Minimum size in byte of a PUS TC packet

/* Definition of subaddresses used by ICU-ASW to send telemetry to the SpaceCraft*/
#define SA_TM_RESET 1U //!< 1553 Subaddress used receive messages to start TM protocol reset
#define SA_TM_PUS_3 11U //!< 1553 Subaddress used to transmit not periodically PUS 3 Service packets
#define SA_EV_AND_PUS_1 12U //!< 1553 Subaddress used to transmit event and acknowledge packets
#define SA_HK_4 13U //!< 1553 Subaddress used to transmit periodic HK4 packets
#define SA_HK_3 14U //!< 1553 Subaddress used to transmit periodic HK3 packets
#define SA_HK_2 15U //!< 1553 Subaddress used to transmit periodic HK2 packets
#define SA_HK_1 16U //!< 1553 Subaddress used to transmit periodic HK1 packets
#define SA_DUMP 17U //!< 1553 Subaddress used to transmit periodic memory dump packets
#define SA_DIAG_1 18U //!< 1553 Subaddress used to transmit diagnostic 1 packets
#define SA_DIAG_0 19U //!< 1553 Subaddress used to transmit diagnostic 2 packets
#define SA_TC 10U //!< 1553 Subaddress used to receive telecommands
#define SA_DTD_DTC 27U //!< 1553 Subaddress used to receive DTD and transmit DTC
#define SA_ATR_ATC 28U //!< 1553 Subaddress used to transmit ATR and receive ATC
#define SA_TIME 29U //!< 1553 Subaddress used to handle time messages
#define SA_WRAP_AROUND 30U //!< 1553 Subaddress used to handle wrap around operation
/**
 * \}
 */

/**
 *  \ingroup MILBUS_MANAGER_TYPES
 *  \{
 */

/**
 * \union TransferDescriptorDataWord_t
 * \brief Format defined for the Distribution Transfer Descriptor data words:
 * - DTD
 * - DTC
 * - ATC
 * - ATR
 * field 3 is called QoS in ATC and DTD structure, error in ATR and DTC
 * structure ECSS-E-ST-50-13C
 */
typedef union {
	uint32_t all_bits;
	struct {
		uint32_t reserved :4, size :12, QoS :1, reset :1, mode :1, SA :5,
				blockCount :8;
	};

} TransferDescriptorDataWord_t;

/**
 * \brief Time Data Word Message using CCSDS CUC Format
 */
typedef uint16_t OBT_TimeData_t[5];

/**
 * \struct SendList_Data
 * \brief Structure defined for manage sendlists. Members are SendList
 * information, number of messages inserted during creation and number of
 * messages read during reading operations
 */
typedef struct {
	SendList_t sendlist;
	uint32_t n_msgs;
} SendListData;

/**
 * \struct Handler_1553_t
 */

typedef struct {
	TransferDescriptorDataWord_t DTC;
	TransferDescriptorDataWord_t DTD;
	TransferDescriptorDataWord_t ATC;
	TransferDescriptorDataWord_t ATR;
	OBT_TimeData_t time_message;
	uint16_t last_msg_index_used;
	uint16_t current_comm_frame;
	uint8_t last_sendlist_executed;
	uint8_t last_sendlist_read;
	uint8_t last_sendlist_processed;
} Handler_1553_t;

/**
 * \}
 */

#endif /* MILBUS_H_ */
